baseURL = "http://192.168.10"
locale = "en-us"
title = "Nobleinux | Systems & Infrastructure Engineer"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[menu]
  [[menu.main]]
    name = "Works"
    url = "/#selected-works"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/#experience"
    weight = 3
  [[menu.main]]
    name = "About"
    pageRef = "/about/"
    weight = 4
  [[menu.main]]
    name = "Skills"
    url = "/#skills"
    weight = 2
