baseURL = "http://192.168.10"
locale = "en-us"
title = "Nobleinux | Systems & Infrastructure Engineer"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[menu]
  [[menu.main]]
    name = "Works"
    pageRef = "/works/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    pageRef = "/experience/"
    weight = 3
  [[menu.main]]
    name = "About"
    pageRef = "/about/"
    weight = 4
  [[menu.main]]
    name = "skills"
    pageRef = "#skills"
    weight = 2
